spring:
  datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/dnb21
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
server:
  port: 9000
  error:
    include-message: always